baseURL = 'https://example.org/'
languageCode = 'en-us'
disableKinds = ['taxonomy']
title = 'Francesco Tomaselli'
theme = 'Typo'

[params]
# Config
math = true

profilePic = 'static/profile_pic.png'

# Intro text
homeIntro = true
homeIntroTitle = 'Hi!'
homeIntroContent = """
    I am an Italian Software Engineer with a strong foundation 
    in computer science and a passion for solving complex problems.
    I am interested in a range of topics, including algorithms, 
    distributed systems, databases, and information retrieval.
"""

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/tomaselli-/"

[[params.social]]
name = "medium"
url = "https://medium.com/@tomfran"

[[params.social]]
name = "github"
url = "https://github.com/tomfran"

[[params.social]]
name = "leetcode"
url = "https://leetcode.com/tomfran/"

[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"


[[params.menu]]
name = "resume"
url = "/resume"

[markup]
[markup.highlight]
style = 'algol'
